name: Feature Development and PR Workflow

on:
  workflow_dispatch:
    inputs:
      # feature_branch:
      #   description: 'Feature branch to run the workflow on'
      #   required: true
      #   default: 'feature/*'
      create_pr:
        description: 'Create a Pull Request to Dev(Main) after deployment?'
        type: boolean
        required: true
        default: false
      tf_action:
        description: 'Terraform action to perform'
        type: choice
        required: true
        default: 'plan'
        options:
          - plan
          - apply

jobs:
  terraform-deploy:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    env:
      TF_VERSION: 1.9.0
      GCP_PROJECT_ID: 'neon-well-438222-b6'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: latest
          install_components: 'beta,terraform-tools'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        if: github.event.inputs.tf_action == 'plan' || github.event.inputs.tf_action == 'apply'
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        if: github.event.inputs.tf_action == 'plan' || github.event.inputs.tf_action == 'apply'
        id: plan
        run: terraform plan -out=tfplan -input=false
        working-directory: ./terraform
        continue-on-error: true

      - name: Check Terraform Plan Success
        if: steps.plan.outcome != 'success'
        run: |
          echo "Terraform Plan failed. Exiting..."
          exit 1
      - name: Terraform Apply
        if: steps.plan.outcome == 'success' && github.event.inputs.tf_action == 'apply'
        run: terraform apply -auto-approve -input=false tfplan
        working-directory: ./terraform

  create-pr:
    name: Create Pull Request
    needs: terraform-deploy
    if: github.event.inputs.create_pr == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name}}

      - name: Create Pull Request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name}}
          destination_branch: dev
          pr_title: "Merge ${{ github.ref_name}} into Dev"
          pr_body: "This PR merges changes from ${{ github.ref_name}} into Dev after successful deployment of test resources."
          pr_draft: false
          pr_label: "feature, needs-review, automated-pr"
          github_token: ${{ secrets.GH_TOKEN }}