name: Terraform Deployment

on:
  push:
    branches:
      - "feat/*"

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Setup Google Cloud CLI
    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'

    # Authenticate using the Service Account JSON key
    - name: Authenticate to GCP
      run: |
        echo "${{ secrets.GCP_CREDENTIALS }}" > $HOME/gcloud-key.json
        gcloud auth activate-service-account terraform-sa@myzesoftlyproject27.iam.gserviceaccount.com --key-file=$HOME/gcloud-key.json
        gcloud config set project myzesoftlyproject27

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    # Terraform Init
    - name: Terraform Init
      run: terraform init

    # Terraform Format and Validate
    - name: Terraform Sanity Check
      run: |
        terraform fmt -check
        terraform validate

    # Terraform Plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan

    # Terraform Apply
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' || github.ref == startsWith(github.ref, 'refs/heads/feat/')
      run: terraform apply -auto-approve tfplan
