name: GCP Authentication Workflow

on: 
  push:
    branches:
      - main

jobs:
  authenticate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        env:
          GCP_JSON_KEY: ${{ secrets.GCP_JSON_KEY }}
        run: |
          echo "${GCP_JSON_KEY}" > "${HOME}/gcp-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"

      - name: Configure gcloud
        run: gcloud config set project myzesoftlyproject27
