name: Release To Higher Environment Workflow
on:
  workflow_dispatch:
    inputs:
      create_pr:
        description: 'Create a Pull Request'
        type: boolean
        required: true
        default: false
      target_environment:
        description: 'Target environment'
        type: choice
        required: true
        default: 'qa'
        options:
          - qa
          - staging
          - prod

jobs:
  terraform-validate-and-plan:
    name: Terraform Validate and Plan 
    runs-on: ubuntu-latest
    outputs:
      terraform_success: ${{ steps.set-result.outputs.success }}
    env:
      TF_VERSION: 1.9.0
      GCP_PROJECT_ID: ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
        
      - name: Log Workflow Parameters
        run: |
          echo "::group::Workflow Parameters"
          echo "Branch: ${{ github.ref_name }}"
          echo "Target Environment: ${{ github.event.inputs.target_environment }}"
          echo "Create PR: ${{ github.event.inputs.create_pr }}"
          echo "::endgroup::"
          
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
        continue-on-error: false

      - name: Log Authentication Status
        run: |
          echo "::group::GCP Authentication"
          if [[ "${{ steps.auth.outcome }}" == "success" ]]; then
            echo "✅ Successfully authenticated to GCP"
          else
            echo "❌ Failed to authenticate to GCP"
            exit 1
          fi
          echo "::endgroup::"
          
      - name: Set up Cloud SDK
        id: gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: latest
          install_components: 'beta,terraform-tools'
        continue-on-error: false
      
          
      - name: Setup Terraform
        id: terraform-setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
        continue-on-error: false
      
        
      - name: Terraform Init
        id: init
        run: |
          echo "::group::Terraform Init"
          terraform init
          INIT_EXIT_CODE=$?
          if [ $INIT_EXIT_CODE -ne 0 ]; then
            echo "❌ Terraform init failed with exit code $INIT_EXIT_CODE"
            exit $INIT_EXIT_CODE
          else
            echo "✅ Terraform init completed successfully"
          fi
          echo "::endgroup::"
        working-directory: ./terraform
        continue-on-error: true
      
      - name: Check Terraform Init Success
        if: steps.init.outcome != 'success'
        run: |
          echo "❌ Terraform Init failed. See logs for details. Exiting..."
          exit 1

      - name: Terraform Validate
        id: validate
        run: |
          echo "::group::Terraform Validate"
          terraform validate
          VALIDATE_EXIT_CODE=$?
          if [ $VALIDATE_EXIT_CODE -ne 0 ]; then
            echo "❌ Terraform validate failed with exit code $VALIDATE_EXIT_CODE"
            exit $VALIDATE_EXIT_CODE
          else
            echo "✅ Terraform validate completed successfully"
          fi
          echo "::endgroup::"
        working-directory: ./terraform
        continue-on-error: true
          
      - name: Check Terraform Validate Success
        if: steps.validate.outcome != 'success'
        run: |
          echo "❌ Terraform Validate failed. See logs for details. Exiting..."
          exit 1
          
      - name: Check and Select Terraform Workspace
        id: workspace
        run: |
          echo "::group::Terraform Workspace"
          # Check if workspace exists
          WORKSPACE_EXISTS=$(terraform workspace list | grep -w "${WORKSPACE_NAME}" || echo "")
          
          if [ -z "$WORKSPACE_EXISTS" ]; then
            echo "Creating new workspace: ${WORKSPACE_NAME}"
            terraform workspace new ${WORKSPACE_NAME}
          else
            echo "Selecting existing workspace: ${WORKSPACE_NAME}"
            terraform workspace select ${WORKSPACE_NAME}
          fi
          
          echo "Current workspace: $(terraform workspace show)"
          echo "::endgroup::"
        working-directory: ./terraform
        env:
          WORKSPACE_NAME: ${{ github.event.inputs.target_environment }}
        continue-on-error: false
      
      - name: Terraform Plan
        if:  steps.validate.outcome == 'success'
        id: terraform-plan
        run: |
          echo "::group::Terraform Plan"
          terraform plan -out=tfplan -input=false
          PLAN_EXIT_CODE=$?
          if [ $PLAN_EXIT_CODE -ne 0 ]; then
            echo "❌ Terraform plan failed with exit code $PLAN_EXIT_CODE"
            exit $PLAN_EXIT_CODE
          else
            echo "✅ Terraform plan completed successfully"
          fi
          echo "::endgroup::"
        working-directory: ./terraform
        continue-on-error: true
        
      - name: Check Terraform Plan Success
        if: steps.terraform-plan.outcome != 'success'
        run: |
          echo "❌ Terraform Plan failed. See logs for details. Exiting..."
          exit 1
          
      - name: Summarize Terraform Deployment
        id: set-result
        run: |
          echo "::group::Deployment Summary"
          echo "Branch: ${{ github.ref_name }}"
          echo "Lower Environment: ${{ github.ref_name }}"
          echo "Higher Environment: ${{ github.event.inputs.target_environment }}"
          echo "Terraform Workspace: ${{ github.event.inputs.target_environment }}"
          echo "::endgroup::"
          echo "success=true" >> $GITHUB_OUTPUT

  create-pr:
    name: Create Pull Request
    needs: terraform-validate-and-plan
    if: |
      github.event.inputs.create_pr == 'true' && needs.terraform-validate-and-plan.result == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
              
      - name: Create Pull Request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: ${{ github.event.inputs.target_environment }}
          pr_title: "Merge ${{ github.ref_name }} into  ${{ github.event.inputs.target_environment }}"
          pr_body: "This PR merges changes from ${{ github.ref_name }} into ${{ github.event.inputs.target_environment }} after successful validation of test resources."
          pr_draft: false
          github_token: ${{ secrets.GH_TOKEN }}